chore: code format check

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -10,22 +10,20 @@ defaults:
 
 env:
     GO_VERSION: 1.23.4
-    PNAME: loadgen
+    PNAME: agent
 
 jobs:
-    unit_test:
+    format_check:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout current repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 path: ${{ env.PNAME }}
 
             - name: Checkout framework repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 repository: infinilabs/framework
                 path: framework
 
@@ -33,7 +31,82 @@ jobs:
               uses: actions/checkout@v4
               with:
                 ref: main
-                fetch-depth: 0
+                repository: infinilabs/framework-vendor
+                path: vendor
+
+            - name: Set up go toolchain
+              uses: actions/setup-go@v5
+              with:
+                go-version: ${{ env.GO_VERSION }}
+                check-latest: false
+                cache: true
+
+            - name: Check go toolchain
+              run: go version
+              
+            - name: Run make format
+              shell: bash
+              run: |
+                echo Home path is $HOME
+                export WORKBASE=$HOME/go/src/infini.sh
+                export WORK=$WORKBASE/$PNAME
+
+                # for test workspace
+                mkdir -p $HOME/go/src/
+                ln -s $GITHUB_WORKSPACE $WORKBASE
+                
+                # check work folder
+                ls -lrt $WORKBASE/
+                ls -alrt $WORK
+
+                # for unit test
+                cd $WORK
+                echo Formating code at $PWD ...
+                make format
+                if [ $? -ne 0 ]; then
+                  echo "make format failed, please check make output"
+                  exit 1
+                fi
+
+            - name: Check for changes after format
+              id: check-changes
+              shell: bash
+              run: |
+                export WORKBASE=$HOME/go/src/infini.sh
+                export WORK=$WORKBASE/$PNAME
+
+                # for foramt check
+                cd $WORK
+                if [[ $(git status --porcelain | grep -c " M .*\.go$") -gt 0 ]]; then
+                  echo "go format detected formatting changes"
+                  echo "changes=true" >> $GITHUB_OUTPUT
+                else
+                  echo "go format no changes found"
+                  echo "changes=false" >> $GITHUB_OUTPUT
+                fi
+            
+            - name: Fail workflow if changes after format
+              if: steps.check-changes.outputs.changes == 'true'
+              run: exit 1
+
+    unit_test:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout current repository
+              uses: actions/checkout@v4
+              with:
+                path: ${{ env.PNAME }}
+
+            - name: Checkout framework repository
+              uses: actions/checkout@v4
+              with:
+                repository: infinilabs/framework
+                path: framework
+
+            - name: Checkout framework-vendor
+              uses: actions/checkout@v4
+              with:
+                ref: main
                 repository: infinilabs/framework-vendor
                 path: vendor
 
@@ -74,13 +147,11 @@ jobs:
             - name: Checkout current repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 path: ${{ env.PNAME }}
 
             - name: Checkout framework repository
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0
                 repository: infinilabs/framework
                 path: framework
 
@@ -88,7 +159,6 @@ jobs:
               uses: actions/checkout@v4
               with:
                 ref: main
-                fetch-depth: 0
                 repository: infinilabs/framework-vendor
                 path: vendor
 
